export type BundledGuideLang = "ja" | "en";

/** 製品ユーザーガイドをベースに、このアプリ向けに調整した本文。 */
const GUIDE_JA = [
  "# Tipsboard ユーザーガイド",
  "",
  "Tipsboard は、小さなページをリンクでつなげて知識を育てるためのボードです。既存のフォルダ階層を保ちながら、書きながら関連ページへ道を作れます。",
  "",
  "## このガイドの構成",
  "",
  "1. **はじめに** — メモの単位、タイトル、保存、Vault",
  "2. **画面と操作** — サイドバー、検索、タブ、画面履歴、KANBAN",
  "3. **メモの書き方** — Markdown 風の記法",
  "4. **ページをつなげる** — 内部リンク、外部リンク、タグ",
  "5. **関連リンク（Links パネル）** — バックリンクと 2 ホップ",
  "6. **添付（画像・ファイル）**",
  "7. **タイトル変更時の内部リンク** — 任意の一括書き換え",
  "8. **キーボードショートカット**",
  "",
  "## はじめに",
  "",
  "- メモ本文の**先頭行がタイトル**です。保存時にファイル名にも反映されます。",
  "- メモは選択した **Vault フォルダ**以下の Markdown ファイルです。既存の階層構造をそのまま使えます。新規メモはまず Vault 直下の `inbox/` に保存されます。`inbox` のメモには未整理であることを示す表示が出ます。**移動先を提案**から既存フォルダへの整理候補を確認できます。",
  "- 編集内容は**自動保存**されます。状態はヘッダーに表示されます。",
  "- **新規メモ**: Tipsboard パネルにフォーカスがあるとき `Ctrl+N` / `⌘N`（検索欄などネイティブ入力にフォーカスがあるときは無効）。コマンド **Tipsboard: New Note**、左サイドバーの **+**、カード一覧が空のときの画面ボタンからも作成できます。",
  "- 1 メモに 1 話題を意識し、長くなったら分割して `[リンク]` でつなげると読みやすくなります。",
  "",
  "## 画面と操作",
  "",
  "### 左のアクティビティバー",
  "",
  "| アイコン | 説明 |",
  "|----------|------|",
  "| 本 | このユーザーガイド |",
  "| カード格子 | メモ一覧（カード表示） |",
  "| 列 | KANBAN |",
  "| + | 新規メモ |",
  "| 歯車 | 表示言語、JSON の Import / Export |",
  "",
  "### 検索",
  "",
  "ヘッダー中央の検索で、タイトル・タグ・本文から候補が出ます。Enter を押すとカード一覧へ戻り、検索語で絞り込まれたカードだけを表示します。特定のノートを直接開きたいときは、候補ドロップダウンの行をクリックします。",
  "",
  "### タブ",
  "",
  "リスト表示では、ヘッダー直下に**ノート**または**タグ検索**（`#タグ`）のタブが並びます。",
  "",
  "- **通常クリック**で別ノートへ移るとき、未保存の変更があると確認ダイアログが出ます。",
  "- **Cmd / Ctrl を押したまま**内部リンク・タグ・関連リンクのカードをクリックすると、**確認なしで**別タブを開けます。同じノート path や同じタグは 1 タブにまとまります。",
  "- **×** で閉じられますが、**最後の 1 枚は閉じられません**。コマンド **Tipsboard: Close active tab**（パネルがアクティブなとき `Ctrl+Alt+Shift+W` / `⌘⌥⇧W`、ネイティブ入力フォーカス中は無効）。",
  "",
  "### 画面履歴（NavMemory）",
  "",
  "Tipsboard **内だけ**の戻る・進むです（VS Code 本体のエディタ履歴とは別です）。",
  "",
  "| 操作 | ショートカット（例） |",
  "|------|---------------------|",
  "| 戻る | `Alt+←`、`Ctrl+[` / `⌘[`、マウス戻る（多くは button 3） |",
  "| 進む | `Alt+→`、`Ctrl+]` / `⌘]`、マウス進む（多くは button 4） |",
  "",
  "環境によって **Browser Back / Forward** 相当のキーが届くこともあります。`Ctrl+]` / `⌘]` は IDE のインデントなどと競合することがあるため、必要ならキーバインドを変更してください。",
  "",
  "履歴には、開いているタブ、検索バーの内容、一覧／KANBAN／このガイドの表示切替などが含まれます。**新しい画面へ進む操作の直前**に現在状態が積まれ、**進む**の列はそのとき空になります。Vault のフォルダ変更や JSON の Import でも履歴はリセットされます。",
  "",
  "**次のときは戻る・進むは動きません**: 未保存離脱などの**確認ダイアログ表示中**、ヘッダー検索など**ネイティブ入力**（INPUT / TEXTAREA / SELECT）にフォーカスがあるとき。",
  "",
  "### KANBAN",
  "",
  "ボード・列・カードは `.tipsboard/kanban.json` の**メタデータ**です。カードの移動だけではメモ本文は変わりません。メモのパス変更に合わせてカード参照が更新される場合があります。",
  "",
  "列内では、カードの**上半分**にドロップするとそのカードの前、**下半分**だと後ろ、列の余白なら末尾に並び替えられます。",
  "",
  "### メモを開いているとき",
  "",
  "- 右側の操作から**ピン留め**、**HTML エクスポート**（未保存の変更を含む）、**削除**ができます。",
  "- HTML 内の画像は Vault 内のファイルを参照します。Vault を移すとリンクが切れることがあります。",
  "- ノート下部の **Links** パネルで、外向きリンク・バックリンク・2 ホップ・New Links を確認できます（詳細は後述）。",
  "",
  "## メモの書き方",
  "",
  "本文は **Markdown 風**の記法です。エディタでは装飾つきで編集し、このガイドではレンダリング結果を確認できます。",
  "",
  "### 見出し",
  "",
  "```text",
  "# 大きな見出し",
  "## 小見出し",
  "### さらに小さく",
  "```",
  "",
  "### 文字の強調",
  "",
  "```text",
  "**重要なこと**",
  "*補足*",
  "~~取り消した内容~~",
  "```",
  "",
  "表示: **重要なこと** / *補足* / ~~取り消した内容~~",
  "",
  "### 引用",
  "",
  "```text",
  "> 引用や注意書き",
  "> 複数行も可",
  "```",
  "",
  "### リスト",
  "",
  "```text",
  "- 箇条書き",
  "- もう1つ",
  "",
  "1. 手順1",
  "2. 手順2",
  "```",
  "",
  "箇条書き行末で Enter を押すと次の項目が続きます。`Tab` / `Shift+Tab` でインデントを増減できます。",
  "",
  "### コード",
  "",
  "インラインは `` ` `` で囲みます（例: `npm install`）。複数行はバッククォート 3 つで囲みます。",
  "",
  "```text",
  "docker compose up",
  "grep pattern file.md",
  "```",
  "",
  "### 表（GFM / multimd-table）",
  "",
  "```text",
  "| 項目 | 内容 |",
  "| --- | --- |",
  "| 状態 | **進行中** |",
  "| 関連 | [決定メモ] |",
  "```",
  "",
  "エディタでは表をクリックするとソースに戻って編集できます。",
  "",
  "### Mermaid 図表",
  "",
  "コードブロックの開始行を ```mermaid にし、図の内容を書いて ``` で閉じます。",
  "",
  "```mermaid",
  "flowchart TD",
  "  Idea[アイデア] --> Note[ページ]",
  "  Note --> Link[リンクでつなぐ]",
  "```",
  "",
  "表示された図をクリックするとソース編集に戻ります。",
  "",
  "### 数式（LaTeX / KaTeX）",
  "",
  "HTML エクスポートやこのガイドの表示では **KaTeX** で描画されます。エディタ上はソースのままです。",
  "",
  "- **インライン**: `\\( ... \\)`。`$ ... $` を使うときは前後に空白があると安全です。",
  "- **ブロック**: 単独行の `$$` で上下を囲みます。",
  "",
  "インライン例: \\(f'(x) = \\lim_{h \\to 0} \\dfrac{f(x+h)-f(x)}{h}\\)",
  "",
  "$$",
  "\\sum_{k=1}^{n} k = \\frac{n(n+1)}{2}",
  "$$",
  "",
  "### 仕切り線",
  "",
  "```text",
  "---",
  "```",
  "",
  "## ページをつなげる",
  "",
  "リンクでメモ同士に道を作れます。存在しないページへのリンクを開くと、新規作成のきっかけになります。",
  "",
  "### 内部リンク",
  "",
  "```text",
  "[決定メモ]",
  "[用語集]",
  "```",
  "",
  "`[` と `]` でタイトル文字列を囲みます（二重ブラケットの Wiki 形式ではありません）。**Cmd / Ctrl+クリック**で別タブに開く操作は「**タブ**」を参照してください。",
  "",
  "### 外部リンク",
  "",
  "```text",
  "[https://example.com]",
  "[参考資料 https://example.com]",
  "```",
  "",
  "### タグ",
  "",
  "```text",
  "#会議",
  "#あとで読む",
  "```",
  "",
  "`#` の直後に空白なしで続けるとタグとして扱われ、検索やリンクの入口になります。",
  "",
  "## 関連リンク（Links パネル）",
  "",
  "メモを開いたとき、エディタの下に表示されます。",
  "",
  "- **Links**: このメモから張っているリンクと、**このメモへ直接リンクしているメモ**（バックリンク）。",
  "- **New Links**: 相手から参照されているが、本文ではまだリンクしていない関係。",
  "- **2 ホップ**: このメモからリンクした先が、さらにリンクしているメモ。",
  "",
  "## 添付（画像・ファイル）",
  "",
  "エディタへ**Shift を押しながらドラッグ＆ドロップ**すると Vault に取り込まれます。通常のドロップだけでは挿入されません。",
  "",
  "- **画像**（PNG / JPEG / GIF / WebP）: `assets/images/` に保存され、`![説明文](assets/images/....webp)` のように挿入されます。",
  "- **画像以外**: `assets/files/` に保存され、`[表示名](assets/files/....csv)` のような標準 Markdown リンクとして挿入されます（実行ファイルなど一部拡張子は除外）。リンクをクリックすると OS の既定アプリで開きます。",
  "",
  "```text",
  "![説明文](assets/images/....webp)",
  "[データ](assets/files/....csv)",
  "```",
  "",
  "埋め込み画像をクリックすると拡大プレビューが開きます（ホイールや `+` / `-` で拡大縮小、`0` でリセット）。",
  "",
  "## タイトル変更時の内部リンク",
  "",
  "先頭行のタイトルを変えて保存すると、**正規化後のタイトル**（`normalizeTitle`）が以前と異なる場合に限り、確認ダイアログが出ることがあります。",
  "",
  "対象は、コードフェンス**外**の **`[ … ]` 形式**で、旧タイトルの正規化名に一致する文言です。**`[表示名](path)` の標準 Markdown リンクは対象外**です。",
  "",
  "ダイアログには、該当ノート数と旧／新タイトルが示されます。",
  "",
  "- **書き換える**（ラベルは UI 言語に準拠）: 対象ノートを順に保存し、一致する表記を更新します。",
  "- **キャンセル**: どのファイルも変更しません。",
  "",
  "検出のために Vault をディスクから読み直すため、ほかのエディタで先にリンクを足した場合も取りこぼしにくくなっています。",
  "",
  "## キーボードショートカット",
  "",
  "| 操作 | ショートカット |",
  "|------|----------------|",
  "| カード一覧 | `Ctrl+Shift+L` / `⌘⇧L` |",
  "| KANBAN | `Ctrl+Shift+K` / `⌘⇧K` |",
  "| 新規メモ | `Ctrl+N` / `⌘N`（パネルがアクティブ、ネイティブ入力フォーカス時は無効） |",
  "| 戻る（NavMemory） | `Alt+←`、`Ctrl+[` / `⌘[` など（上記「画面履歴」参照） |",
  "| 進む（NavMemory） | `Alt+→`、`Ctrl+]` / `⌘]` など |",
  "| タブを閉じる | `Ctrl+Alt+Shift+W` / `⌘⌥⇧W` |",
  "| リストのインデント | `Tab` / `Shift+Tab` |",
  "",
  "## Tipsboard らしい書き方",
  "",
  "- タイトルだけで内容が想像できるようにする。",
  "- 1 メモに 1 話題を意識する。",
  "- 関連メモへ `[リンク]` を張る。",
  "- 古い情報には `#deprecated` などタグや補足を付ける。",
].join("\n");

const GUIDE_EN = [
  "# Tipsboard User Guide",
  "",
  "Tipsboard is a board for growing knowledge by connecting small pages with links. It keeps your existing folder hierarchy while helping you create paths between pages as you write.",
  "",
  "## How this guide is organized",
  "",
  "1. **Getting started** — notes, titles, saving, Vault",
  "2. **The UI** — sidebar, search, tabs, navigation history, KANBAN",
  "3. **Writing notes** — Markdown-like syntax",
  "4. **Connecting pages** — internal links, external links, tags",
  "5. **The Links panel** — backlinks and two-hop discovery",
  "6. **Attachments** — images and other files",
  "7. **Renaming and inbound wiki links** — optional bulk rewrite",
  "8. **Keyboard shortcuts**",
  "",
  "## Getting started",
  "",
  "- The **first line of the body is the title** and drives the saved filename.",
  "- Notes are Markdown files under your **Vault folder**. Existing nested folders are preserved. New notes are saved to `inbox/` at the vault root first. Inbox notes show a filing notice, and **Suggest folder** can recommend existing folders to move them into.",
  "- Edits **save automatically**; status appears in the header.",
  "- **New note**: `Ctrl+N` / `⌘N` while the Tipsboard panel is focused (skipped in native inputs such as the search box). Also **Tipsboard: New Note**, the sidebar **+**, or the on-screen button when the grid is empty.",
  "- Prefer one topic per note; split long pages and link the pieces with `[Title]`.",
  "",
  "## The UI",
  "",
  "### Activity bar (left)",
  "",
  "| Icon | Purpose |",
  "|------|---------|",
  "| Book | This guide |",
  "| Cards | Note grid |",
  "| Columns | KANBAN boards |",
  "| + | New note |",
  "| Gear | Language, JSON import/export |",
  "",
  "### Search",
  "",
  "The header field searches titles, tags, and bodies. Press Enter to return to the card grid filtered by the current query. Click a dropdown row when you want to open a specific note directly.",
  "",
  "### Tabs",
  "",
  "In list mode, a strip under the header holds **note** tabs or **tag search** tabs (`#tag`).",
  "",
  "- **Normal clicks** that leave the current note may prompt to discard unsaved changes.",
  "- **Cmd / Ctrl+click** on internal links, tags, or cards in Related / New Links opens another tab **without** that prompt. Duplicate note paths or tags share one tab.",
  "- Close with ×; **the last tab cannot be closed**. Command **Tipsboard: Close active tab** (`Ctrl+Alt+Shift+W` / `⌘⌥⇧W` when the panel is focused; skipped in native text fields).",
  "",
  "### Screen history (NavMemory)",
  "",
  "Back and forward apply to **Tipsboard UI state only**—not VS Code’s global editor history.",
  "",
  "| Action | Examples |",
  "|--------|----------|",
  "| Back | `Alt+←`, `Ctrl+[` / `⌘[`, mouse back (often button 3) |",
  "| Forward | `Alt+→`, `Ctrl+]` / `⌘]`, mouse forward (often button 4) |",
  "",
  "Some environments also deliver **Browser Back / Forward** (or **XF86Back** / **XF86Forward**). `Ctrl+]` / `⌘]` may clash with IDE commands such as indent—remap in Keyboard Shortcuts if needed.",
  "",
  "History includes open tabs, the search bar, and whether you are on the grid, KANBAN, or this guide. Moving to a **new** shell of state clears the forward stack; changing the vault folder or importing JSON clears both stacks.",
  "",
  "**Back/forward are ignored** while a discard **confirmation dialog** is open, or while focus is in a native field (**INPUT**, **TEXTAREA**, **SELECT**, including the search box).",
  "",
  "### KANBAN",
  "",
  "Boards live in `.tipsboard/kanban.json`. Moving cards updates metadata only—not note bodies. Card pointers may follow note path changes after saves.",
  "",
  "Within a column, drop on a card’s **top half** to insert before it, **bottom half** to insert after, or on empty space below the list to move to the **end**.",
  "",
  "### While a note is open",
  "",
  "- Use the right-side actions to **pin**, **export HTML** (includes unsaved edits), or **delete**.",
  "- Exported HTML references images inside the Vault; moving the Vault can break those links.",
  "- The **Links** panel below the editor shows outgoing links, backlinks, two-hop, and New Links (see below).",
  "",
  "## Writing notes",
  "",
  "Bodies use **Markdown-like** notation. The editor decorates syntax while you type; this guide shows rendered HTML for reference.",
  "",
  "### Headings",
  "",
  "```text",
  "# Large heading",
  "## Subheading",
  "### Smaller",
  "```",
  "",
  "### Emphasis",
  "",
  "```text",
  "**Important**",
  "*Note*",
  "~~Removed text~~",
  "```",
  "",
  "Result: **Important** / *Note* / ~~Removed text~~",
  "",
  "### Quotes",
  "",
  "```text",
  "> Quote or callout",
  "> Multiple lines ok",
  "```",
  "",
  "### Lists",
  "",
  "```text",
  "- Bullet",
  "- Another item",
  "",
  "1. Step one",
  "2. Step two",
  "```",
  "",
  "Press Enter at the end of a bullet to continue the list. `Tab` / `Shift+Tab` change indentation.",
  "",
  "### Code",
  "",
  "Wrap inline text in single backticks (`npm install`). Use triple-backtick fences for blocks:",
  "",
  "```text",
  "docker compose up",
  "grep pattern file.md",
  "```",
  "",
  "### Tables (GFM / multimd-table)",
  "",
  "```text",
  "| Area | Status |",
  "| --- | --- |",
  "| Draft | **In progress** |",
  "| Related | [Decisions] |",
  "```",
  "",
  "Click a rendered table in the editor to edit the Markdown source.",
  "",
  "### Mermaid diagrams",
  "",
  "Open a fenced block with ```mermaid, add diagram lines, then close with ```.",
  "",
  "```mermaid",
  "flowchart TD",
  "  Idea[Idea] --> Note[Page]",
  "  Note --> Link[Connect with links]",
  "```",
  "",
  "Click the rendered diagram to return to source editing.",
  "",
  "### LaTeX math (KaTeX)",
  "",
  "Formulas render with **KaTeX** in HTML export and in this guide; the editor shows the raw delimiters.",
  "",
  "- **Inline**: `\\( ... \\)`. With `$ ... $`, keep **spaces outside** the dollars when possible.",
  "- **Block**: `$$` on its own line above and below the expression.",
  "",
  "Inline sample: \\( \\int_0^1 x^2\\,dx = \\tfrac{1}{3} \\)",
  "",
  "$$",
  "\\mathbf{A}\\mathbf{x} = \\mathbf{b}",
  "$$",
  "",
  "### Dividers",
  "",
  "```text",
  "---",
  "```",
  "",
  "## Connecting pages",
  "",
  "Links create paths between notes. Following a link to a missing page can create that page.",
  "",
  "### Internal links",
  "",
  "```text",
  "[Decisions]",
  "[Glossary]",
  "```",
  "",
  "Use a single pair of brackets (not double Wiki brackets). **Cmd / Ctrl+click** to open another tab is described under **Tabs** above.",
  "",
  "### External links",
  "",
  "```text",
  "[https://example.com]",
  "[Docs https://example.com]",
  "```",
  "",
  "### Tags",
  "",
  "```text",
  "#meeting",
  "#read-later",
  "```",
  "",
  "Write `#` immediately followed by the tag name (no space).",
  "",
  "## The Links panel",
  "",
  "Shown below the editor when a note is open.",
  "",
  "- **Links**: outgoing links plus notes that **link directly here** (backlinks).",
  "- **New Links**: the other note links here but this body does not link back yet.",
  "- **Two-hop**: notes linked from destinations you already link to.",
  "",
  "## Attachments",
  "",
  "**Shift+drag** files into the editor to copy them into the Vault. A plain drop does nothing.",
  "",
  "- **Images** (PNG / JPEG / GIF / WebP): saved under `assets/images/` as `![description](assets/images/....webp)`.",
  "- **Other files**: saved under `assets/files/` as `[label](assets/files/....csv)` (some executable-like extensions are skipped). Click the link to open with your **OS default application**.",
  "",
  "```text",
  "![description](assets/images/....webp)",
  "[dataset](assets/files/....csv)",
  "```",
  "",
  "Click an embedded image for a large preview (wheel or `+` / `-` to zoom, `0` to reset).",
  "",
  "## Renaming and inbound wiki links",
  "",
  "After you change the opening title and save, a dialog may appear **only when** normalized title (`normalizeTitle`) differs from before.",
  "",
  "It targets **`[ … ]` bracket text** outside fenced code that still matches the old normalized title. Standard Markdown **`[Label](path)`** links are **not** rewritten.",
  "",
  "The dialog lists how many notes match and shows the old and new titles.",
  "",
  "- **Rewrite links** (label follows UI language): saves each affected note in order and updates matching bracket text.",
  "- **Cancel**: leaves every file unchanged.",
  "",
  "Detection rereads the vault from disk so links added outside Tipsboard are still found.",
  "",
  "## Keyboard shortcuts",
  "",
  "| Action | Shortcut |",
  "|--------|----------|",
  "| Card grid | `Ctrl+Shift+L` / `⌘⇧L` |",
  "| KANBAN | `Ctrl+Shift+K` / `⌘⇧K` |",
  "| New note | `Ctrl+N` / `⌘N` (panel focused; skipped in native inputs) |",
  "| Back (NavMemory) | `Alt+←`, `Ctrl+[` / `⌘[`, etc. (see **Screen history**) |",
  "| Forward (NavMemory) | `Alt+→`, `Ctrl+]` / `⌘]`, etc. |",
  "| Close tab | `Ctrl+Alt+Shift+W` / `⌘⌥⇧W` |",
  "| List indent | `Tab` / `Shift+Tab` |",
  "",
  "## Writing the Tipsboard way",
  "",
  "- Titles should stand alone.",
  "- Prefer one topic per note.",
  "- Link related notes with `[Title]`.",
  "- Mark stale pages with tags such as `#deprecated`.",
].join("\n");

export function getBundledUserGuideMarkdown(lang: BundledGuideLang): string {
  return lang === "ja" ? GUIDE_JA : GUIDE_EN;
}
