export type BundledGuideLang = "ja" | "en";

/** 製品ユーザーガイドをベースに、このアプリ向けに調整した本文。 */
const GUIDE_JA = [
  "# Tipsboard ユーザーガイド",
  "",
  "Tipsboard は、小さなページをリンクでつなげて知識を育てるためのボードです。フォルダで先に分類するより、書きながら関連ページへ道を作ることを大切にしています。",
  "",
  "## このガイドの内容",
  "",
  "- まず覚えること: メモの単位、タイトル、自動保存、Vault、リンク表記の一括更新（スクショ付き）。",
  "- 書き方の基本: 見出し、強調、引用、リスト、コード、表、Mermaid、数式（LaTeX）、仕切り線。",
  "- ページをつなげる: 内部リンク、外部リンク、タグ。",
  "- リンク・バックリンク・2ホップ: 画面下部の Links パネル。",
  "- 画像とアイコン: ドロップで挿入、`![alt](パス)`、`[ページ名.icon]`。",
  "- アプリの操作: アクティビティバー、検索、KANBAN、ショートカット、JSON。",
  "",
  "## まず覚えること",
  "",
  "- メモ本文の**先頭行がタイトル**として扱われます（保存時にファイル名にも反映されます）。",
  "- **新規メモ**は `Ctrl+N` / `⌘N`（検索欄やネイティブの入力欄にフォーカスがあるときは無効）。カード一覧が空のときは画面のボタンからも作成できます。",
  "- 編集内容は**自動保存**されます。保存状態はヘッダーに表示されます。",
  "- メモは選択した **Vault フォルダ**以下の `.md` として保存されます。Git やバックアップは Vault 単位で行えます。",
  "- メモが長くなりすぎたら、話題ごとに分けてリンクでつなげると読みやすくなります。",
  "- **タイトル変更**を保存すると、見出し行の **`normalizeTitle` が変わり**、`[旧タイトル]` のような単一ブラケットの内部ウィキリンクに相当する文言がコードフェンス外に少なくとも1か所ある場合だけ、確認ダイアログのあと各ノートを順に保存して書き換えられます（断れば本文はそのまま）。**`[表示名](…​)` の標準Markdownリンクは対象外**です。",
  "- 書き換え候補の検出には **Vault をディスクから再度読んだ内容** が使われます（ほかエディタで先にリンクを足したときやパネルの一覧本文がディスクより遅れているときも取りこぼしを減らすため）。",
  "",
  "![タイトル変更後の内部リンク書き換え確認](https://raw.githubusercontent.com/kyu999/tipsboard-vscode/main/assets/vscode/marketplace/rewrite_internal_link.png)",
  "",
  "**例（上記の画面）**: 該当する `[ … ]` の件数や旧／新タイトルが示され、「書き換える」ですべての対象ノートを順番に保存してリンク表記を更新します。**キャンセル**は一括書き換えを行わず、どのファイルも書き換えません。確認ボタンのラベルは UI の言語設定に合わせて表示されます。",
  "",
  "## 書き方の基本",
  "",
  "本文は **Markdown 風**の記法です。エディタでは装飾つきで編集し、このガイドではレンダリング結果を確認できます。",
  "",
  "### 見出し",
  "",
  "```text",
  "# 大きな見出し",
  "## 小見出し",
  "### さらに小さく",
  "```",
  "",
  "### 文字の強調",
  "",
  "```text",
  "**重要なこと**",
  "*補足*",
  "~~取り消した内容~~",
  "```",
  "",
  "表示: **重要なこと** / *補足* / ~~取り消した内容~~",
  "",
  "### 引用",
  "",
  "```text",
  "> 引用や注意書き",
  "> 複数行も可",
  "```",
  "",
  "### リスト",
  "",
  "```text",
  "- 箇条書き",
  "- もう1つ",
  "",
  "1. 手順1",
  "2. 手順2",
  "```",
  "",
  "**エディタでの操作**: 箇条書き行末で Enter を押すと次の項目が続きます。`Tab` / `Shift+Tab` でインデントを増減できます。",
  "",
  "### コード",
  "",
  "インラインはバッククォート1つで短いコードを囲みます。例として文中で `npm install` のように書けます。",
  "",
  "複数行はバッククォート3つで囲みます:",
  "",
  "```text",
  "docker compose up",
  "grep pattern file.md",
  "```",
  "",
  "### 表（GFM / multimd-table）",
  "",
  "```text",
  "| 項目 | 内容 |",
  "| --- | --- |",
  "| 状態 | **進行中** |",
  "| 関連 | [決定メモ] |",
  "```",
  "",
  "表示時に読みやすく整形されます。エディタでは表をクリックするとソースに戻って編集できるモードになります。",
  "",
  "### Mermaid 図表",
  "",
  "フローチャートなどは **Mermaid** という記法で書けます。複数行のコードブロックと同じように、本文を**バッククォート3つで上下から囲みます**。違いは、**上側の ``` のすぐ後ろに `mermaid` と書く一行**を最初に置くことです。その下に図の内容を書き、最後にバッククォートだけの一行で閉じます。",
  "",
  "```mermaid",
  "flowchart TD",
  "  Idea[アイデア] --> Note[ページ]",
  "  Note --> Link[リンクでつなぐ]",
  "```",
  "",
  "エディタでは図として表示されます。直したいときは、表示されている図のあたりをクリックすると編集用のソース表示に戻ります。",
  "",
  "### 数式（LaTeX / KaTeX）",
  "",
  "HTML をエクスポートしたときやこのガイドのように Markdown を HTML にした表示では、**KaTeX** で数式が描画されます。エディター上は数式のソースがそのまま見えます。",
  "",
  "- **インライン**: `\\( ... \\)` で囲む。`$ ... $` で囲むときは、**前後に空白**があると誤判定を避けやすくなります。",
  "- **ブロック（中央寄せ）**: 単独行の `$$` で上下から囲む。",
  "",
  "インライン例: \\(f'(x) = \\lim_{h \\to 0} \\dfrac{f(x+h)-f(x)}{h}\\)",
  "",
  "$$",
  "\\sum_{k=1}^{n} k = \\frac{n(n+1)}{2}",
  "$$",
  "",
  "### 仕切り線",
  "",
  "```text",
  "---",
  "```",
  "",
  "話題の切り替わりや区切りとして使えます。",
  "",
  "## ページをつなげる",
  "",
  "リンクを書くとメモ同士に道ができます。まだ存在しないページへのリンクは、クリック時に新規作成のきっかけになります。",
  "",
  "### 内部リンク（ページリンク）",
  "",
  "```text",
  "[決定メモ]",
  "[用語集]",
  "```",
  "",
  "`[` と `]` でタイトル文字列を囲みます（Wiki 形式の二重ブラケットではありません）。",
  "",
  "### 外部リンク",
  "",
  "```text",
  "[https://example.com]",
  "[参考資料 https://example.com]",
  "```",
  "",
  "URL 形式はリンクとして開きます。",
  "",
  "### タグ",
  "",
  "```text",
  "#会議",
  "#あとで読む",
  "```",
  "",
  "`#` の直後に空白なしで続けるとタグとして扱われ、検索・リンクの入口になります。",
  "",
  "## リンク・バックリンク・2ホップ",
  "",
  "- **Links**: このメモから張っているリンクと、**このメモへ直接リンクしているメモ**（バックリンク）。",
  "- **New Links**: 本文側ではまだリンクしていないが、相手から参照されている関係。",
  "- **2ホップリンク**: このメモからリンクした先が、さらにリンクしているメモ。",
  "",
  "バックリンクを見ると、「この用語はどこで使われているか」「この決定の背景はどこか」をたどりやすくなります。",
  "",
  "## 画像とアイコン",
  "",
  "### 画像の挿入",
  "",
  "画像ファイルをエディタへ**ドラッグ＆ドロップ**すると、Vault 内に取り込まれ、本文へ **Markdown 画像**として挿入されます。",
  "",
  "```text",
  "![説明文](assets/images/....webp)",
  "```",
  "",
  "### ページアイコン記法",
  "",
  "一覧カードなどでは、メモ内の**最初の画像**がプレビューに使われることがあります。",
  "",
  "別メモのタイトルを `[ページ名.icon]` の形で書くと、アイコン表示用の参照として解釈されます。倍数指定は `[ページ名.icon*3]` のように書けます。",
  "",
  "### Ctrl+I（アイコン記法の挿入）",
  "",
  "`Ctrl+I`（Mac も同様）で、**いま編集中のメモのタイトル**をアイコン記法として挿入できます。オートコンプリートで候補を選んでいるときは、そのラベルが優先されます。続けて操作すると `*2`・`*3` のように個数が増える動きになります。",
  "",
  "## アプリでの操作",
  "",
  "### アクティビティバー（左）",
  "",
  "| アイコン | 説明 |",
  "|----------|------|",
  "| 本 | このユーザーガイド |",
  "| フォルダ | Vault のパス表示・フォルダ変更 |",
  "| カード格子 | メモ一覧 |",
  "| 列 | KANBAN |",
  "| 歯車 | 表示言語、JSON の Import / Export |",
  "",
  "### 検索",
  "",
  "ヘッダー中央の検索で、タイトル・タグ・本文から候補が出ます。Enter で先頭候補を開くこともできます。",
  "",
  "### KANBAN",
  "",
  "ボード・列・カードは `.tipsboard/kanban.json` に保存される**メタデータ**です。カードの移動だけではメモ本文は書き換わりません。メモのパス変更に合わせてカード参照が更新される場合があります。",
  "",
  "### HTML エクスポート",
  "",
  "メモを開いているときのヘッダーメニューから、現在の本文（未保存の変更を含む）を HTML でダウンロードできます。画像は Vault 内のファイルを参照します。Vault の場所を変えるとリンクが切れることがあります。",
  "",
  "### キーボードショートカット一覧",
  "",
  "| 操作 | ショートカット |",
  "|------|----------------|",
  "| カード一覧 | `Ctrl+Shift+L` / `⌘⇧L` |",
  "| KANBAN | `Ctrl+Shift+K` / `⌘⇧K` |",
  "| 一つ前の画面へ戻る | `Alt+←` または `Ctrl+[` / `⌘[` |",
  "| 新規メモ | `Ctrl+N` / `⌘N`（入力系フォーカス時は無効） |",
  "| リストのインデント | `Tab` / `Shift+Tab` |",
  "| アイコン記法の挿入 | `Ctrl+I` |",
  "",
  "## Tipsboard らしい書き方（短く）",
  "",
  "- タイトルだけで内容が想像できるようにする。",
  "- 1 メモに 1 話題を意識する。",
  "- 関連メモへ `[リンク]` を張る。",
  "- 古い情報には `#deprecated` などタグや補足を付ける。",
].join("\n");

const GUIDE_EN = [
  "# Tipsboard User Guide",
  "",
  "Tipsboard is a board for growing knowledge by connecting small pages with links. Instead of organizing everything into folders first, you create paths between pages while you write.",
  "",
  "## What this guide covers",
  "",
  "- First things to know: notes, titles, autosave, Vault, optional bulk inbound link rewrite after a rename (screenshot).",
  "- Writing basics: headings, emphasis, quotes, lists, code, tables, Mermaid, LaTeX math, dividers.",
  "- Connecting notes: internal links, external links, tags.",
  "- Links, backlinks, two-hop: the Links panel below the editor.",
  "- Images and icons: drag-and-drop, `![alt](path)`, `[Page title.icon]`.",
  "- Using Tipsboard: activity bar, search, KANBAN, shortcuts, JSON.",
  "",
  "## First things to know",
  "",
  "- The **first line of the body is the title** (and drives the saved filename).",
  "- **New note**: `Ctrl+N` / `⌘N` (disabled while focus is in the search box or another native input). Use the on-screen button when the grid is empty.",
  "- Notes **save automatically**. Status appears in the header.",
  "- Everything lives under your chosen **Vault folder** as `.md` files. Backup and Git operate on that folder.",
  "- When a note feels too long, split by topic and link the pieces.",
  "- Saving a **title change** prompts to rewrite inbound wiki **`[ … ]`** text elsewhere (and inside the same body) **only after** normalization changes and brackets outside fenced code still match the prior title **by `normalizeTitle`**. Standard Markdown **`[Display](path-or-url)`** links stay untouched. Tip: detection rereads vault bodies from disk so links added outside Tipsboard are still found.",
  "",
  "![Confirm rewriting inbound wiki link labels after a save](https://raw.githubusercontent.com/kyu999/tipsboard-vscode/main/assets/vscode/marketplace/rewrite_internal_link.png)",
  "",
  "**What’s on screen**: the number of matching notes plus the previous and new title. Choosing **Rewrite links** (label follows your UI language) saves each affected note in turn and replaces matching bracket text. **Cancel** leaves every file unchanged.",
  "",
  "## Writing basics",
  "",
  "Bodies use **Markdown-like** notation. The editor decorates syntax while you type; this guide shows rendered HTML for reference.",
  "",
  "### Headings",
  "",
  "```text",
  "# Large heading",
  "## Subheading",
  "### Smaller",
  "```",
  "",
  "### Emphasis",
  "",
  "```text",
  "**Important**",
  "*Note*",
  "~~Removed text~~",
  "```",
  "",
  "Result: **Important** / *Note* / ~~Removed text~~",
  "",
  "### Quotes",
  "",
  "```text",
  "> Quote or callout",
  "> Multiple lines ok",
  "```",
  "",
  "### Lists",
  "",
  "```text",
  "- Bullet",
  "- Another item",
  "",
  "1. Step one",
  "2. Step two",
  "```",
  "",
  "**Editor behavior**: pressing Enter at the end of a bullet continues the list. `Tab` / `Shift+Tab` change indentation.",
  "",
  "### Code",
  "",
  "Inline text uses single backticks, like `npm install` inside a sentence.",
  "",
  "Use triple-backtick fences for multiple lines:",
  "",
  "```text",
  "docker compose up",
  "grep pattern file.md",
  "```",
  "",
  "### Tables (GFM / multimd-table)",
  "",
  "```text",
  "| Area | Status |",
  "| --- | --- |",
  "| Draft | **In progress** |",
  "| Related | [Decisions] |",
  "```",
  "",
  "Tables render in a readable layout. Click inside a rendered table in the editor to jump back to Markdown source.",
  "",
  "### Mermaid diagrams",
  "",
  "Flowcharts and similar diagrams use **Mermaid**. Use the same triple-backtick wrapper as a multi-line code block, but **put `mermaid` right after the opening backticks** on the first line. Add your diagram lines below, then close with a line that is only three backticks.",
  "",
  "```mermaid",
  "flowchart TD",
  "  Idea[Idea] --> Note[Page]",
  "  Note --> Link[Connect with links]",
  "```",
  "",
  "The editor renders it as a diagram; click the diagram area when you want to edit the source again.",
  "",
  "### LaTeX math (KaTeX)",
  "",
  "When Markdown is turned into HTML (**Export HTML** or this guide), formulas are rendered with **KaTeX**. In the editor you still see the raw delimiters.",
  "",
  "- **Inline**: wrap with `\\( ... \\)`. You can also use `$ ... $`, but keep **spaces outside the dollars** to avoid clashes with normal text.",
  "- **Block**: use `$$` on its own line above and below the expression.",
  "",
  "Inline sample: \\( \\int_0^1 x^2\\,dx = \\tfrac{1}{3} \\)",
  "",
  "$$",
  "\\mathbf{A}\\mathbf{x} = \\mathbf{b}",
  "$$",
  "",
  "### Dividers",
  "",
  "```text",
  "---",
  "```",
  "",
  "## Connecting pages",
  "",
  "Links create paths between notes. Opening a link to a missing note can create that note.",
  "",
  "### Internal links",
  "",
  "```text",
  "[Decisions]",
  "[Glossary]",
  "```",
  "",
  "Use a single pair of brackets around the title text (not double Wiki brackets).",
  "",
  "### External links",
  "",
  "```text",
  "[https://example.com]",
  "[Docs https://example.com]",
  "```",
  "",
  "### Tags",
  "",
  "```text",
  "#meeting",
  "#read-later",
  "```",
  "",
  "Write `#` immediately followed by the tag name (no space). Tags help search and navigation.",
  "",
  "## Links, backlinks, two-hop",
  "",
  "- **Links**: outgoing links from this note plus notes that **link directly here** (backlinks).",
  "- **New Links**: relationships where the other note links here but this body does not link back yet.",
  "- **Two-hop links**: notes linked from destinations you already link to.",
  "",
  "Use these to answer “where is this mentioned?” and “what surrounds this decision?”.",
  "",
  "## Images and icons",
  "",
  "### Images",
  "",
  "Drag an image into the editor. Tipsboard copies it into the Vault and inserts a normal Markdown image:",
  "",
  "```text",
  "![description](assets/images/....webp)",
  "```",
  "",
  "### Page icons",
  "",
  "The grid may use the **first image** inside a note as card artwork.",
  "",
  "Write `[Other page.icon]` (optional multiplier `[Other page.icon*3]`) to reference another note’s icon thumbnail.",
  "",
  "### Ctrl+I shortcut",
  "",
  "`Ctrl+I` inserts icon notation for the **note you are editing**. When autocomplete is active, its selected label wins. Repeated use bumps multipliers such as `*2`, `*3`.",
  "",
  "## Using Tipsboard",
  "",
  "### Activity bar",
  "",
  "| Icon | Purpose |",
  "|------|---------|",
  "| Book | This guide |",
  "| Folder | Vault path / change folder |",
  "| Cards | Note grid |",
  "| Columns | KANBAN boards |",
  "| Gear | Language + JSON import/export |",
  "",
  "### Search",
  "",
  "The header field searches titles, tags, and bodies. Press Enter to jump to the first hit.",
  "",
  "### KANBAN",
  "",
  "Boards live in `.tipsboard/kanban.json`. Moving cards updates metadata only; it does not rewrite note bodies. Card pointers may follow note path changes after saves.",
  "",
  "### HTML export",
  "",
  "From the header menu while a note is open, export the current editor HTML (including unsaved edits). Images reference Vault files—moving the Vault can break those paths.",
  "",
  "### Shortcuts",
  "",
  "| Action | Shortcut |",
  "|--------|----------|",
  "| Card grid | `Ctrl+Shift+L` / `⌘⇧L` |",
  "| KANBAN | `Ctrl+Shift+K` / `⌘⇧K` |",
  "| Go back | `Alt+←` or `Ctrl+[` / `⌘[` |",
  "| New note | `Ctrl+N` / `⌘N` (disabled in inputs) |",
  "| List indent | `Tab` / `Shift+Tab` |",
  "| Insert icon notation | `Ctrl+I` |",
  "",
  "## Writing the Tipsboard way (short)",
  "",
  "- Titles should stand alone.",
  "- Prefer one topic per note.",
  "- Link related notes with `[Title]`.",
  "- Mark stale pages with tags such as `#deprecated`.",
].join("\n");

export function getBundledUserGuideMarkdown(lang: BundledGuideLang): string {
  return lang === "ja" ? GUIDE_JA : GUIDE_EN;
}
